version: "3.8"

services:

  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - "5713:5713"
    environment:
      VITE_API_URL: http://api:8000
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]

  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_URL: mongodb://db/anime
    volumes:
      - ./backend:/app
    command: ["npm", "run", "dev"]

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - anime:/data/db

volumes:
  anime:
